---
# tasks file for spark
#- name: Copy Spark
#  copy:
#    src: spark-2.2.0-bin-hadoop2.7.tgz
#    dest: /opt/
#    owner: root
#    group: root  

- name: Donwload Spark
  get_url:
     url: http://mirror.nohup.it/apache/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
     dest: /opt/spark-2.2.0-bin-hadoop2.7.tgz
     mode: 0440

- name: Extract Spark tgz
  unarchive:
    src: /opt/spark-2.2.0-bin-hadoop2.7.tgz
    dest: /opt/

- name: Ensure Export file exists
  copy:
    content: ""
    dest: /etc/profile.d/exports.sh
    force: no
    group: root
    owner: root
    mode: 0555

- name: Export Spark home
  lineinfile:
    path: /etc/profile.d/exports.sh
    state: present
    insertafter: EOF
    line: 'export SPARK_HOME=/opt/spark-2.2.0-bin-hadoop2.7'

- name: Export Path
  lineinfile:
    path: /etc/profile.d/exports.sh
    state: present
    insertafter: EOF
    line: 'export PATH=$PATH:$SPARK_HOME/bin'

- name: Source evn variables
  shell: /etc/profile.d/exports.sh
